### PR TITLE
msm8992: OC GPU to 700Mhz

### PR DESCRIPTION
**Pull request by msdx321**
Tested on several phones. A liitle bit hotter but still stable.

~ 10% performance improve

By the way, you should create a branch to contain OC kernel codes

Might need adjust some other setting such as bus freq

### CODE REVIEW

**Comment by AndropaX** [comment]
Could you provide link to source ?

**Comment by msdx321** [comment]
https://github.com/msdx321/Resurrected-Kernel/commit/473e3aa39f4786765f7b18dcc2e0dc2d71cedee0

**Comment by AndropaX** [comment]
I mean from where you have this.

**Comment by msdx321** [comment]
By myself

**Comment by AndropaX** [comment]
Ok, but on which you based ?

**Comment by AndropaX** [comment]
Anyway merged to new branch, but i want to read something about this...

**Pull request closed without merging**
